<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

<div class="container">
    <h1 class="text-primary text-center">Question Form</h1>

    <br>

    <form action="<?php echo $this->getUrl('faq/index/save', ['_secure' => true]);?>" method="POST">
        <div class="mb-3">
            <label class="form-label font-weight-bolder">Full Name</label>
            <input class="form-control" type="text" name="fullName" placeholder="Enter Full Name" aria-label="default input example">
        </div>

        <div class="mb-3">
            <label class="form-label font-weight-bolder">Email</label>
            <input class="form-control" type="email" name="email" placeholder="Enter Full Name" aria-label="default input example">
        </div>

        <div class="mb-3">
            <label class="form-label font-weight-bolder">Question</label>
            <input class="form-control" type="text" name="question" placeholder="Enter Full Name" aria-label="default input example">
        </div>

        <div class="text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous">
</script>